### ISSUE TITLE
Trying to import csv with too many columns throw error

### ISSUE THREAD

**Issue by sagargupta** [WebTales/rubedo#1458] opened 2016-10-17 23:02 UTC
Tried uploading a csv as products creation mode with 83 columns and it throws error: Le fichier doit doit être au format CSV.

Removing some columns and it works well. This must be fixed and there shouldn't be any limit for number of columns in the csv file. 83 columns isn't much when trying to migrate to Rubedo. Users won't be able to migrate properly.

**Comment by Alexandru-Dobre** [comment] 2016-10-18 08:20
There is no such limit on csv imports. This is most likely caused by server configuration (upload file size limits). Your file is simply rejected by the server because it is too big for this limits. Closing this as it is not a Rubedo issue but a server configuration error.

**Closed as completed by Alexandru-Dobre** 2016-10-18 08:20 UTC
